apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-game
spec:
  selector:
    matchLabels:
      app: dice-game
  replicas: 2
  template:
    metadata:
      labels:
        app: dice-game
    spec:
      containers:
        - name: dice-game
          image: nanajanashia/argocd-app:1.0
          ports:
            - containerPort: 8080
